source 'https://rubygems.org'

gem 'colorize'
gem 'faraday'
gem 'google-api-client'
gem 'hashie'
gem 'json'
gem 'meowcop'
gem 'pry'
gem 'rake'
gem 'rspec'
gem 'rubocop'
gem 'signet'
gem 'websocket-eventmachine-client'
